name: Docker Test

on: [push]

jobs:
  job-vm:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo This job does not specify a container.
          echo It runs directly on the virtual machine.
        name: Run on VM
  
  job-container:
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - run: |
          echo This job does specify a container.
          echo It runs in the container instead of the VM.
        name: Run in container

      - run: |
          cat /etc/redhat-release
          echo It runs in the container instead of the VM.
        name: Run in container
