name: Docker Test

on: [push]

jobs:
  job-ubuntu_latest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: install b2
        run: |
          wget -q https://github.com/samueldeng/boost_build/releases/download/v1.0/boost_build_centos7.tar.gz
          tar -xzf boost_build_centos7.tar.gz
          rm boost_build_centos7.tar.gz

      - name: Run on VM
        run: |
          ls -la .
          echo $PWD
          PATH=$PATH:$PWD/boost_build_centos7/bin
          b2 --toolset=gcc -j8
  
  job-docker_centos_7_5:
    runs-on: ubuntu-latest
    container: centos:7.5.1804
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: install base software
        run: |
          yum install -y wget gcc-c++

      - name: install b2 software
        run: |
          wget -q https://github.com/samueldeng/boost_build/releases/download/v1.0/boost_build_centos7.tar.gz
          tar -xzf boost_build_centos7.tar.gz
          rm boost_build_centos7.tar.gz

      - name: Run in container
        run: |
          cat /etc/redhat-release
          ls -la .
          echo $PWD
          PATH=$PATH:$PWD/boost_build_centos7/bin
          b2 --toolset=gcc -j8