name: Docker Test

on: [push]

jobs:
  run-on-docker:

    runs-on: ubuntu-latest

    steps:
    - name: My first step
      uses: docker://centos:7

    - name: checkout
      uses: actions/checkout@v2

    - name: show os version
      run: cat /etc/redhat-release

    - name: Run a one-line script
      run: echo Hello, world!

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
