name: Docker Test

on: [push]

jobs:
  job-ubuntu_latest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: install b2
        run: |
          wget -q https://github.com/samueldeng/boost_build/releases/download/v1.0/boost_build_centos7.tar.gz
          tar -xzf boost_build_centos7.tar.gz
          rm boost_build_centos7.tar.gz

      - name: Run on VM
        run: |
          ls -la .
          echo $PWD
          PATH=$PATH:$PWD/boost_build_centos7/bin
          b2 --toolset=gcc -j8
  
  job-docker_centos_7_5:
    runs-on: ubuntu-latest
    container: centos:7.5.1804
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: install base software
        run: |
          yum install -y wget gcc-c++

      - name: install b2 software
        run: |
          wget -q https://github.com/samueldeng/boost_build/releases/download/v1.0/boost_build_centos7.tar.gz
          tar -xzf boost_build_centos7.tar.gz
          rm boost_build_centos7.tar.gz
          
      - name: install cpplint
        run: |
          wget -q https://github.com/cpplint/cpplint/archive/1.4.5.tar.gz
          tar xzf 1.4.5.tar.gz

      - name: cpplint check
        run: |
          cpplint-1.4.5/cpplint.py --linelength=120 --counting=detailed $(find . -name *.h -or -name *.cpp | grep -vE "^./yats/3rd/" | grep -vE "^./boost_build_centos7" | grep -vE "^./cpplint-1.4.5" )


      - name: install gcc filter
        uses: Trass3r/setup-cpp@master
        
      - name: build
        run: |
          cat /etc/redhat-release
          ls -la .
          echo $PWD
          PATH=$PATH:$PWD/boost_build_centos7/bin
          b2 --toolset=gcc -j8
      
